Metrics/MethodLength:
   Enabled: false
AllCops:
  AutoCorrect: true
  TargetRubyVersion: 2.7
Lint/UnreachableLoop:
   Enabled: false
Layout/EndOfLine:
   Enabled: false
Metrics/AbcSize:
   Enabled: false
Naming/MethodName: 
   AutoCorrect: false       

