Metrics/MethodLength:
   Enabled: false
AllCops:
  AutoCorrect: true
  TargetRubyVersion: 3.0.0
Lint/UnreachableLoop:
   Enabled: false
Layout/EndOfLine:
   Enabled: false
Metrics/AbcSize:
   Enabled: false
Naming/MethodName: 
   AutoCorrect: false
   Enabled: false       
Naming/FileName:
   Enabled: false

