# rubocop config
Metrics/MethodLength:
   Enabled: false
AllCops:
  AutoCorrect: true
  TargetRubyVersion: 2.5
Layout/EndOfLine:
   Enabled: false
Metrics/AbcSize:
   Enabled: false
Naming/MethodName:
   AutoCorrect: false
   Enabled: false
Naming/FileName:
   Enabled: false
Naming/VariableName:
   Enabled: false
Style/GlobalVars:
   Enabled: false
Layout/TrailingBlankLines:
   Enabled: false
