# rubocop config
Metrics/MethodLength:
   Enabled: false
AllCops:
  AutoCorrect: true
  TargetRubyVersion: 2.6
Lint/UnreachableLoop:
   Enabled: false
Layout/EndOfLine:
   Enabled: false
Metrics/AbcSize:
   Enabled: false
Naming/MethodName:
   AutoCorrect: false
   Enabled: false
Naming/FileName:
   Enabled: false
Naming/VariableName:
   Enabled: false
Gemspec/DateAssignment: # new in 1.10
  Enabled: false
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: false
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: false
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/DeprecatedConstants: # new in 1.8
  Enabled: false
Lint/DuplicateBranch: # new in 1.3
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: false
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: false
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
  Gemspec/DateAssignment: # new in 1.10
  Enabled: false
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: false
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: false
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/DeprecatedConstants: # new in 1.8
  Enabled: false
Lint/DuplicateBranch: # new in 1.3
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: false
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: false
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
