name: test cello
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:

        include:
          - os: macos-latest
            RUBY: 2.7
            
          - os: macos-11
            RUBY: 2.7
           
          - os: ubuntu-latest
            RUBY: 2.7

          - os: windows-latest
            RUBY: 2.7
    steps:
          - uses: actions/checkout@v1
          - name: Run info
            run: echo 'running ruby ${{matrix.RUBY}}'
          - name: Install bundler
            run: gem install bundler
          - name: Install Dependencies
            run: bundle install
          - name: install rubocop
            run: gem install rubocop
          - name: run rubocop
            run: rubocop
          - run: run install getting started from main on ruby ${{matrix.RUBY}} on ${{matrix.os}}
          
