name: test cello
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:

        include:
          - os: macos-latest
            RUBY: 2.7
            
          - os: macos-11
            RUBY: 2.7
           
          - os: ubuntu-latest
            RUBY: 2.7

          - os: windows-latest
            RUBY: 2.7
    steps:
          - uses: actions/checkout@v1
          - uses: ruby/setup-ruby@v1
            with:
              ruby-version: ${{matrix.RUBY}} # Not needed with a .ruby-version file
        #bundler-cache: true # runs 'bundle install' and caches installed gems automatically  
          - name: Install Dependencies
            run: bundle install
          - name: setup git config
            run: |
              git config user.name "GitHub Actions Bot"
              git config user.email "<74566464+Pandademic@users.noreply.github.com>"
          - name: install rubocop
            run: gem install rubocop
          - name: run rubocop
            run: rubocop -A
          - name: push to github
            run: | 
               git stage -A
               git commit  -m "Rubocop fixes"
               git push origin master
          - name: run install getting started from main on ruby ${{matrix.RUBY}} on ${{matrix.os}}
            run: ruby core/cello.rb add getting-started --main
          
